version: "3.3"
name: midpoint
services:
  postgresql:
    image: postgres:13-alpine
    container_name: midpoint_db
    hostname: host_midpoint_db
    environment:
     - POSTGRES_PASSWORD_FILE=/run/secrets/mp_database_password.txt
     - POSTGRES_USER=midpoint
     - POSTGRES_INITDB_ARGS=--lc-collate=en_US.utf8 --lc-ctype=en_US.utf8
    ports:
     - 5432:5432
    networks:
     - midpoint_net
    secrets:
     - mp_database_password.txt
    volumes:
     - midpoint_db_data:/var/lib/postgresql/data

  midpoint:
    image: evolveum/midpoint:4.7-support
    container_name: midpoint_server
    hostname: host_midpoint_server
    depends_on:
     - postgresql
    ports:
      - 8080:8080
    environment:
     - REPO_DATABASE_TYPE=postgresql
     - REPO_HOST=host_midpoint_db
     - REPO_DATABASE=midpoint
     - REPO_USER=midpoint
     - REPO_PASSWORD_FILE=/run/secrets/mp_database_password.txt
     - REPO_MISSING_SCHEMA_ACTION
     - REPO_UPGRADEABLE_SCHEMA_ACTION
     - REPO_SCHEMA_VERSION_IF_MISSING
     - REPO_SCHEMA_VARIANT
     - MP_KEYSTORE_PASSWORD_FILE=/run/secrets/mp_keystore_password.txt
     - MP_MEM_MAX
     - MP_MEM_INIT
     - MP_JAVA_OPTS
     - TZ
    networks:
     - midpoint_net
    secrets:
     - mp_database_password.txt
     - mp_keystore_password.txt
    volumes:
     - midpoint_server_data:/opt/midpoint/var

networks:
  midpoint_net:    
    driver: bridge

secrets:
  mp_database_password.txt:
    file: ./secrets/database_password.txt
  mp_keystore_password.txt:
    file: ./secrets/keystore_password.txt
    
volumes:
  midpoint_db_data:
    name: midpoint_db_data
  midpoint_server_data:
    name: midpoint_server_data