version: "3.4"
name: sistema_rrhh
services:
  postgresql:
    image: postgres:13-alpine
    container_name: rrhh_db
    restart: always
    environment:
      - POSTGRES_PASSWORD=qwe123
      - POSTGRES_USER=rrhh
      - POSTGRES_INITDB_ARGS=--lc-collate=en_US.utf8 --lc-ctype=en_US.utf8
    ports:
      - 5434:5432
    networks:
      - rrhh_net
    volumes:
      - rrhh_db_data:/var/lib/postgresql/data
      - ./scripts-db:/docker-entrypoint-initdb.d/:ro

networks:
  rrhh_net:    
    driver: bridge

volumes:
  rrhh_db_data:
    name: rrhh_db_data
